// Autogenerated from Pigeon (v3.0.3), do not edit directly.
// See also: https://pub.dev/packages/pigeon
#import "app.h"
#import <FlutterMacOS/FlutterMacOS.h>

#if !__has_feature(objc_arc)
#error File requires ARC to be enabled.
#endif

static NSDictionary<NSString *, id> *wrapResult(id result, FlutterError *error) {
  NSDictionary *errorDict = (NSDictionary *)[NSNull null];
  if (error) {
    errorDict = @{
        @"code": (error.code ? error.code : [NSNull null]),
        @"message": (error.message ? error.message : [NSNull null]),
        @"details": (error.details ? error.details : [NSNull null]),
        };
  }
  return @{
      @"result": (result ? result : [NSNull null]),
      @"error": errorDict,
      };
}
static id GetNullableObject(NSDictionary* dict, id key) {
  id result = dict[key];
  return (result == [NSNull null]) ? nil : result;
}
static id GetNullableObjectAtIndex(NSArray* array, NSInteger key) {
  id result = array[key];
  return (result == [NSNull null]) ? nil : result;
}


@interface PBCInstalledApplication ()
+ (PBCInstalledApplication *)fromMap:(NSDictionary *)dict;
- (NSDictionary *)toMap;
@end

@implementation PBCInstalledApplication
+ (instancetype)makeWithName:(nullable NSString *)name
    path:(nullable NSString *)path
    icon:(nullable NSString *)icon
    pinyin:(nullable NSString *)pinyin {
  PBCInstalledApplication* pigeonResult = [[PBCInstalledApplication alloc] init];
  pigeonResult.name = name;
  pigeonResult.path = path;
  pigeonResult.icon = icon;
  pigeonResult.pinyin = pinyin;
  return pigeonResult;
}
+ (PBCInstalledApplication *)fromMap:(NSDictionary *)dict {
  PBCInstalledApplication *pigeonResult = [[PBCInstalledApplication alloc] init];
  pigeonResult.name = GetNullableObject(dict, @"name");
  pigeonResult.path = GetNullableObject(dict, @"path");
  pigeonResult.icon = GetNullableObject(dict, @"icon");
  pigeonResult.pinyin = GetNullableObject(dict, @"pinyin");
  return pigeonResult;
}
- (NSDictionary *)toMap {
  return [NSDictionary dictionaryWithObjectsAndKeys:(self.name ? self.name : [NSNull null]), @"name", (self.path ? self.path : [NSNull null]), @"path", (self.icon ? self.icon : [NSNull null]), @"icon", (self.pinyin ? self.pinyin : [NSNull null]), @"pinyin", nil];
}
@end

@interface PBCServiceCodecReader : FlutterStandardReader
@end
@implementation PBCServiceCodecReader
- (nullable id)readValueOfType:(UInt8)type 
{
  switch (type) {
    case 128:     
      return [PBCInstalledApplication fromMap:[self readValue]];
    
    default:    
      return [super readValueOfType:type];
    
  }
}
@end

@interface PBCServiceCodecWriter : FlutterStandardWriter
@end
@implementation PBCServiceCodecWriter
- (void)writeValue:(id)value 
{
  if ([value isKindOfClass:[PBCInstalledApplication class]]) {
    [self writeByte:128];
    [self writeValue:[value toMap]];
  } else 
{
    [super writeValue:value];
  }
}
@end

@interface PBCServiceCodecReaderWriter : FlutterStandardReaderWriter
@end
@implementation PBCServiceCodecReaderWriter
- (FlutterStandardWriter *)writerWithData:(NSMutableData *)data {
  return [[PBCServiceCodecWriter alloc] initWithData:data];
}
- (FlutterStandardReader *)readerWithData:(NSData *)data {
  return [[PBCServiceCodecReader alloc] initWithData:data];
}
@end

NSObject<FlutterMessageCodec> *PBCServiceGetCodec() {
  static dispatch_once_t sPred = 0;
  static FlutterStandardMessageCodec *sSharedObject = nil;
  dispatch_once(&sPred, ^{
    PBCServiceCodecReaderWriter *readerWriter = [[PBCServiceCodecReaderWriter alloc] init];
    sSharedObject = [FlutterStandardMessageCodec codecWithReaderWriter:readerWriter];
  });
  return sSharedObject;
}


void PBCServiceSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<PBCService> *api) {
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.Service.getInstalledApplicationList"
        binaryMessenger:binaryMessenger
        codec:PBCServiceGetCodec()        ];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(getInstalledApplicationListWithCompletion:)], @"PBCService api (%@) doesn't respond to @selector(getInstalledApplicationListWithCompletion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        [api getInstalledApplicationListWithCompletion:^(NSArray<PBCInstalledApplication *> *_Nullable output, FlutterError *_Nullable error) {
          callback(wrapResult(output, error));
        }];
      }];
    }
    else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.Service.hideApp"
        binaryMessenger:binaryMessenger
        codec:PBCServiceGetCodec()        ];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(hideAppWithError:)], @"PBCService api (%@) doesn't respond to @selector(hideAppWithError:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        FlutterError *error;
        [api hideAppWithError:&error];
        callback(wrapResult(nil, error));
      }];
    }
    else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.Service.pasteToFrontestApp"
        binaryMessenger:binaryMessenger
        codec:PBCServiceGetCodec()        ];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(pasteToFrontestAppWithError:)], @"PBCService api (%@) doesn't respond to @selector(pasteToFrontestAppWithError:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        FlutterError *error;
        [api pasteToFrontestAppWithError:&error];
        callback(wrapResult(nil, error));
      }];
    }
    else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.Service.readClipboardData"
        binaryMessenger:binaryMessenger
        codec:PBCServiceGetCodec()        ];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(readClipboardDataForType:error:)], @"PBCService api (%@) doesn't respond to @selector(readClipboardDataForType:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        NSString *arg_forType = GetNullableObjectAtIndex(args, 0);
        FlutterError *error;
        FlutterStandardTypedData *output = [api readClipboardDataForType:arg_forType error:&error];
        callback(wrapResult(output, error));
      }];
    }
    else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.Service.setClipboardData"
        binaryMessenger:binaryMessenger
        codec:PBCServiceGetCodec()        ];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(setClipboardDataData:dataType:error:)], @"PBCService api (%@) doesn't respond to @selector(setClipboardDataData:dataType:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        FlutterStandardTypedData *arg_data = GetNullableObjectAtIndex(args, 0);
        NSString *arg_dataType = GetNullableObjectAtIndex(args, 1);
        FlutterError *error;
        NSNumber *output = [api setClipboardDataData:arg_data dataType:arg_dataType error:&error];
        callback(wrapResult(output, error));
      }];
    }
    else {
      [channel setMessageHandler:nil];
    }
  }
}
