// Autogenerated from Pigeon (v3.0.3), do not edit directly.
// See also: https://pub.dev/packages/pigeon
#import <Foundation/Foundation.h>
@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN

@class PBCInstalledApplication;

@interface PBCInstalledApplication : NSObject
+ (instancetype)makeWithName:(nullable NSString *)name
    path:(nullable NSString *)path
    icon:(nullable NSString *)icon
    pinyin:(nullable NSString *)pinyin;
@property(nonatomic, copy, nullable) NSString * name;
@property(nonatomic, copy, nullable) NSString * path;
@property(nonatomic, copy, nullable) NSString * icon;
@property(nonatomic, copy, nullable) NSString * pinyin;
@end

/// The codec used by PBCService.
NSObject<FlutterMessageCodec> *PBCServiceGetCodec(void);

@protocol PBCService
- (void)getInstalledApplicationListWithCompletion:(void(^)(NSArray<PBCInstalledApplication *> *_Nullable, FlutterError *_Nullable))completion;
- (void)hideAppWithError:(FlutterError *_Nullable *_Nonnull)error;
- (void)pasteToFrontestAppWithError:(FlutterError *_Nullable *_Nonnull)error;
- (nullable FlutterStandardTypedData *)readClipboardDataForType:(NSString *)forType error:(FlutterError *_Nullable *_Nonnull)error;
/// @return `nil` only when `error != nil`.
- (nullable NSNumber *)setClipboardDataData:(FlutterStandardTypedData *)data dataType:(NSString *)dataType error:(FlutterError *_Nullable *_Nonnull)error;
@end

extern void PBCServiceSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<PBCService> *_Nullable api);

NS_ASSUME_NONNULL_END
